server:
  port: 9091
  servlet:
    context-path: /nisum/v1

spring:
  datasource:
    url: jdbc:h2:mem:userservicedb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: nisum
    password: nisum2023

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /nisum/v1/api-docs/swagger-config
    url: /nisum/v1/api-docs

regexp:
  email: ^[A-Za-z0-9+_.-]+@(.+)$
  password: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()?[{}]:;',?/*~$^+=<>]).{8,20}$

secretKey: nisumSecretPlataformaChallenge123**